# Generated by Django 4.2.5 on 2023-10-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название компании')),
                ('date_create', models.DateTimeField(verbose_name='дата создания компании')),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='акция')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='цена')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='companyshares.company', verbose_name='какой компании пренадлежит акция')),
            ],
        ),
    ]
